[ARC-1906] Parsed Quiz Json, added subject page and question page logic
GiorgiMamagulashvili16/QuizApp pull request #2
Opened 2021-11-16 06:31 UTC by GiorgiMamagulashvili16

https://spaceneobank.atlassian.net/browse/ARC-1906

2021-11-16 06:59 UTC, giorgiqemoklidze approved these changes

2021-11-17 12:00 UTC, AnaRusadze requested changes

2021-11-17 12:15 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/quizapp/presentation/question_screen/QuestionPageFragment.kt
> +                    answerAdapter.submitList(state.answerList)
აა გასაგებია, შევცვლი

2021-11-17 12:15 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/quizapp/presentation/question_screen/QuestionPageFragment.kt
> +                checkIsAnswerChecked(isAnswerChecked)
ამ ფუნქციით ვამოწმებ თუმოჩექილია პასუხი, ისე სახელი მეც არ მომხვდა ეხლა თვალში კარგად :დდ

2021-11-17 12:17 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/quizapp/presentation/question_screen/QuestionPageFragment.kt
> +        with(viewModel) {
ეს არ გამოვა იმიტომ რომ vm და args სხვადასხვა ობიქტებია და ერთ with ში არ მუშაობს

2021-11-17 12:27 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/quizapp/presentation/question_screen/QuestionPageFragment.kt
> +                    answerAdapter.submitList(state.answerList)
done

2021-11-17 12:27 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/quizapp/presentation/question_screen/QuestionPageFragment.kt
> +                checkIsAnswerChecked(isAnswerChecked)
done

2021-11-17 12:32 UTC, AnaRusadze approved these changes

2021-11-17 13:19 UTC, AleksandreGalogreBaramidze approved these changes

2021-11-17 13:26 UTC, merged