[ARC-1913] implemented quiz functionality
GiorgiMamagulashvili16/QuizApp pull request #3
Opened 2021-11-19 12:02 UTC by GiorgiMamagulashvili16

https://spaceneobank.atlassian.net/browse/ARC-1913

2021-11-19 12:17 UTC, AnaRusadze requested changes

2021-11-19 12:17 UTC, AnaRusadze commented on app/src/main/java/com/example/quizapp/data/repository/QuizRepo.kt
>  interface QuizRepo {
Repo-ს მაგივრად repository კარგი იქნებოდა, როგორც გუშინ გითხრეს

2021-11-19 12:17 UTC, AnaRusadze commented on app/src/main/java/com/example/quizapp/data/repository/QuizRepoImpl.kt
> +class QuizRepoImpl @Inject constructor(
აქაც რეპოზიტორი

2021-11-19 12:17 UTC, AnaRusadze commented on app/src/main/java/com/example/quizapp/di/RepositoryModule.kt
> +    fun provideQuizRepo(jsonParser: JsonParser, userDataStore: UserDataStore): QuizRepo =
აქაც

2021-11-19 12:17 UTC, AnaRusadze commented on app/src/main/java/com/example/quizapp/presentation/question_screen/QuestionPageFragment.kt
> +        submitDialog!!.setDialog(submitDialogBinding!!)
ჩემი აზრით ფრაგმენტის ონქრიეითში არ დაგჭირდება დიალოგის შექმნა, იქნებ საერთოდ არ მიდის ქუიზის ბოლომდე მომხმარებელი. უშუალოდ დიალოგის ფუნქციაში დაგაიტანე ეს კოდი

2021-11-19 12:17 UTC, AnaRusadze commented on app/src/main/java/com/example/quizapp/presentation/start_screen/StartPageViewModel.kt
>          if (name.isBlank() || name.isEmpty())
name.isBlank() || name.isEmpty() გადააკეთე:
1 isBlank თავისთავად მოიცავს isEmpty-ს ცნებას

2021-11-19 12:17 UTC, AnaRusadze commented on app/src/main/res/drawable/close_btn_bg.xml
> +    <solid android:color="#d6d6d6" />
გადაიტანე ფერების რესურსებში

2021-11-19 12:17 UTC, AnaRusadze commented on app/src/main/res/drawable/ic_quiz_logo.xml
> +        android:fillColor="#FFAA00"
ესეც

2021-11-19 12:17 UTC, AnaRusadze commented on app/src/main/res/xml/home_page_fragment_scene.xml
> +            android:id="@+id/fabLogOut"
შეგიძლია გაითვალისწინო რეკომენდაცია და აიდიების სახელებისთვის შემოკლებული ფორმა არ გამოიყენო. მაგრამ არაა სავალდებულო

2021-11-19 12:25 UTC, andguladzeshio approved these changes

2021-11-19 12:33 UTC, AleksandreGalogreBaramidze commented on app/src/main/java/com/example/quizapp/presentation/start_screen/StartPageViewModel.kt
>          if (name.isBlank() || name.isEmpty())
trim.isBlank() ვარიანტიც თვა გუშინ ბექამ

2021-11-19 12:43 UTC, GiorgiMamagulashvili16 commented on app/src/main/res/drawable/ic_quiz_logo.xml
> +        android:fillColor="#FFAA00"
done

2021-11-19 12:44 UTC, GiorgiMamagulashvili16 commented on app/src/main/res/drawable/close_btn_bg.xml
> +    <solid android:color="#d6d6d6" />
done

2021-11-19 12:44 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/quizapp/presentation/start_screen/StartPageViewModel.kt
>          if (name.isBlank() || name.isEmpty())
done

2021-11-19 12:44 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/quizapp/di/RepositoryModule.kt
> +    fun provideQuizRepo(jsonParser: JsonParser, userDataStore: UserDataStore): QuizRepo =
done

2021-11-19 12:44 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/quizapp/data/repository/QuizRepoImpl.kt
> +class QuizRepoImpl @Inject constructor(
done

2021-11-19 12:44 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/quizapp/data/repository/QuizRepo.kt
>  interface QuizRepo {
done

2021-11-19 13:16 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/quizapp/presentation/question_screen/QuestionPageFragment.kt
> +        submitDialog!!.setDialog(submitDialogBinding!!)
done

2021-11-22 08:12 UTC, AnaRusadze approved these changes

2021-11-22 08:13 UTC, merged