[ARC-1934] Implemented save user feature
GiorgiMamagulashvili16/QuizApp pull request #5
Opened 2021-12-10 09:12 UTC by GiorgiMamagulashvili16

https://spaceneobank.atlassian.net/browse/ARC-1934

2021-12-10 09:22 UTC, AleksandreGalogreBaramidze requested changes

2021-12-10 09:22 UTC, AleksandreGalogreBaramidze commented on app/src/main/java/com/example/quizapp/presentation/leaderboard_screen/LeaderBoardFragment.kt
> +            viewModel.setQuizStats(username)
with გამოიყენე

2021-12-10 09:22 UTC, AleksandreGalogreBaramidze commented on app/src/main/java/com/example/quizapp/presentation/leaderboard_screen/LeaderboardAdapter.kt
> +                    position - 1
კონსტანტაში გაიტანე

2021-12-10 09:22 UTC, AleksandreGalogreBaramidze commented on app/src/main/java/com/example/quizapp/presentation/leaderboard_screen/LeaderboardAdapter.kt
> +                    d("CLICK","sd")
ეს რა არის?????????????????????????????

2021-12-10 09:22 UTC, AleksandreGalogreBaramidze commented on app/src/main/java/com/example/quizapp/presentation/question_screen/QuestionPageViewModel.kt
> +                    totalQuestions = lastIndex + 1
კონსტანტებში გაიტანე

2021-12-10 09:22 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/quizapp/presentation/leaderboard_screen/LeaderboardAdapter.kt
> +                    d("CLICK","sd")
დაშიფრული ინფორმაცია

2021-12-13 10:01 UTC, giorgiqemoklidze approved these changes

2021-12-15 09:25 UTC, AnaRusadze requested changes

2021-12-15 09:25 UTC, AnaRusadze commented on app/src/main/java/com/example/quizapp/presentation/custom_view/BottomSheetCustomView.kt
> +    fun setDataList(newList: MutableList<QuizCredits>) {
აქ არ უნდა იყოს დატას დასეტვა. ეგ რესაიქლერის შიდა ლოგიკაში უნდა დაიწეროს. წინააღმდეგ შემთხვევაში ბოთომშითის გაჯენერიქებას აზრი არ აქვს

2021-12-15 09:25 UTC, AnaRusadze commented on app/src/main/java/com/example/quizapp/presentation/leaderboard_screen/LeaderBoardFragment.kt
> +            bottomSheet.show(childFragmentManager, BOTTOM_SHEET_TAG)
აქ ტაგი რისთვის გჭირდება?

2021-12-15 09:31 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/quizapp/presentation/custom_view/BottomSheetCustomView.kt
> +    fun setDataList(newList: MutableList<QuizCredits>) {
ამას არ ვიყენებ როგორც ჩანს დამავიწყდა წაშლა (

2021-12-15 09:34 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/quizapp/presentation/leaderboard_screen/LeaderBoardFragment.kt
> +            viewModel.setQuizStats(username)
done

2021-12-15 09:34 UTC, GiorgiMamagulashvili16 commented on app/src/main/java/com/example/quizapp/presentation/leaderboard_screen/LeaderboardAdapter.kt
> +                    position - 1
done

2021-12-15 09:40 UTC, AnaRusadze approved these changes

2021-12-15 09:40 UTC, AnaRusadze commented
@AleksandreGalogreBaramidze სანდრომაც დააეფრუვოს და ჩავმერჯავ

2021-12-15 10:00 UTC, AleksandreGalogreBaramidze approved these changes

2021-12-15 10:23 UTC, merged